# @package _global_
dataset:
  outcome_list:
    - diastolic blood pressure

model:
  multi:
    optimizer:
      learning_rate: 0.001
    batch_size: 256
    hidden_units: 144  # CDE hidden dimension
    br_size: 72  # CDE hidden dimension -> br_size
    fc_hidden_units: 36  # output layer, linear hidden dimension
    dropout_rate: 0.1

exp:
  max_epochs: 200
